library(testthat)

# =============================================================================
# Golden Sample Regression Tests
#
# These tests compare pre-recorded R outputs (golden_samples_r.rds) against
# Python lseg-data outputs (truth_lseg_data.json) to verify cross-platform
# consistency.
#
# Golden files are generated by:
#   tests/generate_golden_samples.R   (R samples)
#   tests/generate_golden_samples.py  (Python truth data)
#
# Both require a live Refinitiv terminal. Tests skip if files don't exist.
# =============================================================================

golden_dir <- test_path("golden")

has_r_golden <- function() {
  file.exists(file.path(golden_dir, "golden_samples_r.rds"))
}

has_py_golden <- function() {
  file.exists(file.path(golden_dir, "truth_lseg_data.json"))
}

# Helper: load golden data lazily
load_r_golden <- function() {
  readRDS(file.path(golden_dir, "golden_samples_r.rds"))
}

load_py_golden <- function() {
  jsonlite::fromJSON(file.path(golden_dir, "truth_lseg_data.json"))
}

# =============================================================================
# R golden sample self-consistency checks
# =============================================================================

test_that("R golden samples exist and have expected structure", {
  skip_if(!has_r_golden(), "R golden samples not generated (run tests/generate_golden_samples.R)")

  golden <- load_r_golden()
  expect_type(golden, "list")

  expected_keys <- c(
    "get_data_multi_ric", "get_data_single_ric_pricing",
    "get_data_with_params", "get_history_default_fields",
    "get_history_multi_ric", "get_data_revenue",
    "symbology_ric_to_isin", "historical_pricing_interday",
    "historical_pricing_multi_ric", "search_basic",
    "news_headlines_msft"
  )

  for (key in expected_keys) {
    expect_true(key %in% names(golden),
      info = paste("Missing golden sample:", key)
    )
  }
})

test_that("R golden sample get_data_multi_ric has correct RICs", {
  skip_if(!has_r_golden(), "R golden samples not generated")

  golden <- load_r_golden()
  result <- golden$get_data_multi_ric

  # Result might be a data.frame or have an error field

  if (is.data.frame(result)) {
    expect_true("Instrument" %in% names(result))
    expected_rics <- c("AAPL.O", "GOOG.O", "III.L", "MMM")
    expect_true(all(expected_rics %in% result$Instrument))
  }
})

test_that("R golden sample historical_pricing_interday has pricing columns", {
  skip_if(!has_r_golden(), "R golden samples not generated")

  golden <- load_r_golden()
  result <- golden$historical_pricing_interday

  if (is.data.frame(result)) {
    expect_true(nrow(result) > 0)
    # Historical pricing typically includes CLOSE, HIGH, LOW, OPEN
    pricing_cols <- intersect(names(result), c("TRDPRC_1", "HIGH_1", "LOW_1", "OPEN_PRC"))
    expect_true(length(pricing_cols) > 0,
      info = paste("Expected pricing columns, got:", paste(names(result), collapse = ", "))
    )
  }
})

# =============================================================================
# Cross-validation: R vs Python golden samples
# =============================================================================

test_that("R and Python golden samples agree on get_data_multi_ric", {
  skip_if(!has_r_golden(), "R golden samples not generated")
  skip_if(!has_py_golden(), "Python golden samples not generated")

  r_golden <- load_r_golden()
  py_golden <- load_py_golden()

  r_result <- r_golden$get_data_multi_ric
  py_result <- py_golden$samples$get_data_multi_ric

  skip_if(
    inherits(r_result, "list") && !is.null(r_result$error),
    "R sample had error"
  )
  skip_if(
    is.null(py_result) || length(py_result) == 0,
    "Python sample missing or empty"
  )

  py_df <- as.data.frame(py_result)

  # Both should have the same instruments
  if ("Instrument" %in% names(r_result) && "Instrument" %in% names(py_df)) {
    expect_equal(sort(r_result$Instrument), sort(py_df$Instrument))
  }
})

test_that("R and Python golden samples agree on historical pricing", {
  skip_if(!has_r_golden(), "R golden samples not generated")
  skip_if(!has_py_golden(), "Python golden samples not generated")

  r_golden <- load_r_golden()
  py_golden <- load_py_golden()

  r_result <- r_golden$historical_pricing_interday
  py_result <- py_golden$samples$historical_pricing_interday

  skip_if(!is.data.frame(r_result), "R sample is not a data.frame")
  skip_if(
    is.null(py_result) || length(py_result) == 0,
    "Python sample missing or empty"
  )

  py_df <- as.data.frame(py_result)

  # Row counts should be similar (may differ slightly due to timing)
  expect_true(abs(nrow(r_result) - nrow(py_df)) <= 2,
    info = sprintf(
      "Row count mismatch: R=%d, Python=%d",
      nrow(r_result), nrow(py_df)
    )
  )
})

test_that("R and Python golden samples agree on search results", {
  skip_if(!has_r_golden(), "R golden samples not generated")
  skip_if(!has_py_golden(), "Python golden samples not generated")

  r_golden <- load_r_golden()
  py_golden <- load_py_golden()

  r_result <- r_golden$search_basic
  py_result <- py_golden$samples$search_basic

  skip_if(!is.data.frame(r_result), "R sample is not a data.frame")
  skip_if(
    is.null(py_result) || length(py_result) == 0,
    "Python sample missing or empty"
  )

  # Both should return results for AAPL.O
  expect_true(nrow(r_result) > 0)
})

test_that("R and Python golden samples agree on get_data_with_params", {
  skip_if(!has_r_golden(), "R golden samples not generated")
  skip_if(!has_py_golden(), "Python golden samples not generated")

  r_golden <- load_r_golden()
  py_golden <- load_py_golden()

  r_result <- r_golden$get_data_with_params
  py_result <- py_golden$samples$get_data_with_params

  skip_if(!is.data.frame(r_result), "R sample is not a data.frame")
  skip_if(
    is.null(py_result) || length(py_result) == 0,
    "Python sample missing or empty"
  )

  py_df <- as.data.frame(py_result)

  # Both should have AAPL.O data
  if ("Instrument" %in% names(r_result) && "Instrument" %in% names(py_df)) {
    expect_true("AAPL.O" %in% r_result$Instrument)
    expect_true("AAPL.O" %in% py_df$Instrument)
  }
})

test_that("R and Python golden samples agree on get_data_revenue", {
  skip_if(!has_r_golden(), "R golden samples not generated")
  skip_if(!has_py_golden(), "Python golden samples not generated")

  r_golden <- load_r_golden()
  py_golden <- load_py_golden()

  r_result <- r_golden$get_data_revenue
  py_result <- py_golden$samples$get_data_revenue

  skip_if(!is.data.frame(r_result), "R sample is not a data.frame")
  skip_if(
    is.null(py_result) || length(py_result) == 0,
    "Python sample missing or empty"
  )

  py_df <- as.data.frame(py_result)

  # Compare numeric revenue values with tolerance
  common_cols <- intersect(names(r_result), names(py_df))
  for (col in common_cols) {
    if (is.numeric(r_result[[col]]) && is.numeric(py_df[[col]])) {
      # Revenue figures — use relative tolerance
      expect_equal(r_result[[col]], py_df[[col]],
        tolerance = 1e-4,
        info = paste("Mismatch in column:", col)
      )
    }
  }
})

dump_refinitiv_options("test-golden-samples")
