#' Install Eikon Python environment (Defunct)
#'
#' @description
#' `r lifecycle::badge("defunct")`
#'
#' Python/reticulate support has been removed from RefinitivR.
#' The package now uses a direct JSON connection via httr2.
#' Use RefinitivJsonConnect() or RDConnect() to connect.
#'
#' @param ... All arguments are ignored.
#'
#' @return This function always raises an error.
#' @export
install_eikon <- function(...) {
  .Defunct(msg = "install_eikon() has been removed. RefinitivR no longer requires Python. Use RefinitivJsonConnect() or RDConnect() to connect directly via JSON.")
}


#' Function to check which Refinitiv connection method is active
#'
#' @param verbose boolean defaults to TRUE
#'
#' @return named list with connection properties
#' @keywords internal
#'
#' @examples
#' \dontrun{
#' test <- PropertiesActiveRefinitivObject()
#' }
PropertiesActiveRefinitivObject <- function(verbose = TRUE) {
  if (!is.logical(verbose)) {
    stop(paste("parameter verbose should be logical, but is", verbose))
  }

  ModuleName <- getOption(".RefinitivPyModuleName", "JSON")
  Type <- getOption(".RefinitivPyModuleType", "direct JSON connection through httr2 package")

  if (verbose) {
    message(paste(
      "Refinitiv Connection method =", ModuleName, "\n",
      "Type =", Type
    ))
  }

  return(list("name" = ModuleName, "version" = NA_character_, "Type" = Type))
}


## Connection functions (EikonConnect, RDConnect, RDPConnect, rd_connection)
## have been consolidated into R/connection.R


#' Show the available methods of a Refinitiv connection object
#'
#' @param EikonObject Connection object generated by EikonConnect or RefinitivJsonConnect
#'
#' @return a character vector of attribute names
#' @keywords internal
#'
#' @examples
#' \dontrun{
#' Eikon <- EikonConnect(Eikonapplication_id = "your key")
#' EikonShowAttributes(EikonObject = Eikon)
#' }
EikonShowAttributes <- function(EikonObject) {
  if (is.null(EikonObject)) {
    stop("EikonObject should be supplied in function EikonShowAttributes")
  }
  return(names(EikonObject))
}


#' Convert Eikon formula's in human readable names
#'
#' @param names vector of data.frame column names
#' @param SpaceConvertor converts spaces in variables name into one of the following characters ".", "," , "-", "_", default is "."
#'
#' @return a data.frame in which the Eikon formula's are replaced with the Eikon display Name which is the last part of the formula.
#' @keywords internal
#'
#' @details
#' The variables returned by the Eikon API are not always easily guessable upfront.
#' There is no fixed way how variables are returned. EikonNameCleaner improves this by returning UpperCamel case variable names.
#' It does however not turn capitalized words back into lowercase. So e.g. RDN_EXCHD2 will stay RDN_EXCHD2 and "Dividend yield"
#' will return as "Dividend.Yield" (if SpaceConvertor is set as ".")
#'
#' The parameter SpaceConvertor converts spaces into any of the following characters ".", "," , "-", "_".
#' Setting SpaceConvertor to another value will cause no conversion of spaces in the variable names.
#' Space Conversion is highly advisable due to the fact that otherwise issues could occur with accessing columnnames in the returned data.frame
#' as an example "Dividend yield" will turn into "Dividend.Yield" with SpaceConvertor being set as "."
#'
#' @examples
#' Refinitiv:::EikonNameCleaner(c("Instrument", "Company Name", "RDN_EXCHD2", "Operating MIC"))
EikonNameCleaner <- function(names, SpaceConvertor = ".") {
  # 0. Helper Functions ----
  firstup <- function(x) {
    substr(x, 1, 1) <- toupper(substr(x, 1, 1))
    x
  }

  # 1. Main Function ----

  # Extract text between /* and */ using stringi
  # The regex captures text between /* and */, non-greedy
  extracted <- stringi::stri_extract_first_regex(names, "/\\*(.*?)\\*/")

  # Remove the /* and */ from the extracted text
  returnNames <- stringi::stri_replace_all_regex(extracted, "^/\\*|\\*/$", "", vectorize_all = FALSE)

  # For names without /* */, process them by capitalizing the first letter of each word
  no_match <- is.na(returnNames)
  if (any(no_match)) {
    processed_names <- names[no_match]

    # Split by space, capitalize first letter, and rejoin
    processed_names <- stringi::stri_split_fixed(processed_names, " ") |>
      lapply(firstup) |>
      sapply(paste, collapse = " ")

    returnNames[no_match] <- processed_names
  }


  if (isTRUE(SpaceConvertor %in% c(".", ",", "-", "_"))) {
    returnNames <- gsub(x = returnNames, pattern = " ", replacement = SpaceConvertor, perl = TRUE)
  }

  returnNames <- stringi::stri_trans_general(returnNames, "latin-ascii")
  return(returnNames)
}


#' Returns a list of chunked Rics so that api limits can be satisfied
#'
#' @param RICS a vector containing RICS to be requested
#' @param Eikonfields a list of the eikonfields to be requested default NULL, if eikonfields are supplied duration may not be supplied
#' @param MaxCallsPerChunk the maximum amount of apicalls that can be made
#' @param Duration a natural number denoting the amoount of rows asked for in a TimeSeries default NULL, if Duration is supplied Eikonfields may not be supplied
#' @param MaxRicsperChunk  a natural number denoting the maximum amount of Rics that should be available in one call, default is 300.
#'
#' @return a list of splitted RICS that can be returned to guarantee compliance with api limits.
#' @keywords internal
#' @references \url{https://developers.refinitiv.com/eikon-apis/eikon-data-api/docs?content=49692&type=documentation_item}
#'
#' @examples
#' \dontrun{
#' "internal function no examples"
#' }
EikonChunker <- function(RICS, Eikonfields = NULL, MaxCallsPerChunk = 12000, Duration = NULL, MaxRicsperChunk = 300) {
  if (is.null(RICS)) {
    stop("RICS have to be supplid other wise no api call can be made")
  }

  # clean out NA RICS
  RICS <- RICS[!is.na(RICS)]

  if (!is.null(Eikonfields) & is.null(Duration)) {
    totalDataPoints <- length(RICS) * length(Eikonfields)
  } else if (!is.null(Duration) & is.null(Eikonfields)) {
    totalDataPoints <- length(RICS) * Duration
    if (Duration > MaxCallsPerChunk) {
      stop("Duration is too long for even one RIC, Reduce Duration by changing start_date or end_date!")
    }
  } else {
    stop("supply either Duration or Eikonfields")
  }


  message(paste0("the operation you intend to perform will cost ", totalDataPoints, " data points"))

  # Minimum chunks to satisfy both constraints, then distribute evenly
  chunks_dp <- ceiling(totalDataPoints / MaxCallsPerChunk)
  chunks_ric <- if (!is.null(MaxRicsperChunk)) ceiling(length(RICS) / MaxRicsperChunk) else 1L
  n_chunks <- max(chunks_dp, chunks_ric)
  chunk_size <- ceiling(length(RICS) / n_chunks)

  SplittedRics <- split(RICS, ceiling(seq_along(RICS) / chunk_size))
  return(SplittedRics)
}

#' Retry a function call with exponential backoff
#'
#' Retries a zero-argument function up to \code{max_attempts} times.
#' On failure, waits with exponential backoff before retrying.
#'
#' @param fn A zero-argument function to execute. Wrap your call in
#'   \code{function() your_call()} before passing.
#' @param max_attempts Maximum number of attempts (including the first).
#'   Defaults to \code{getOption("refinitiv_max_retries", 2L)}.
#' @param backoff Initial backoff time in seconds. Doubles after each failure, default = 0.5.
#' @param on_failure What to do when all attempts are exhausted.
#'   \code{"stop"} (default) throws an error containing the last failure
#'   message.
#'   \code{"NA"} issues a warning and returns \code{NA} — use this inside
#'   \code{chunked_download()} where per-chunk success is tracked
#'   externally.
#'
#' @details
#' \code{retry()} is the \strong{client-side} retry layer.
#' It guards against transient network errors and unexpected exceptions.
#'
#' \strong{Inside \code{chunked_download()}:} Use
#' \code{retry(fn, max_attempts = 1L, on_failure = "NA")} so that
#' \code{retry()} acts solely as an error-to-\code{NA} converter.
#' The coordinator owns the full retry lifecycle (jittered exponential
#' backoff between rounds, per-chunk tracking).
#'
#' \strong{Standalone callers} (e.g., \code{rd_GetESG}): Use the default
#' \code{max_attempts} (or configure via the
#' \code{refinitiv_max_retries} option) for direct retrying with
#' exponential backoff.
#'
#' It is distinct from two other retry/polling mechanisms in the package:
#' \itemize{
#'   \item \strong{\code{httr2::req_retry()}} inside
#'     \code{send_json_request()} handles HTTP-level transient errors
#'     (429 Too Many Requests, 503 Service Unavailable) transparently
#'     during \code{httr2::req_perform()}.
#'   \item The \strong{server polling loop} in \code{send_json_request()}
#'     handles LSEG-specific JSON responses: async ticket/estimated-duration
#'     polling and retriable error codes (2504, 500, 400).
#' }
#'
#' @return The return value of \code{fn()} on success.
#' @keywords internal
#'
#' @examples
#' # Succeeds immediately:
#' Refinitiv:::retry(function() sum(1, 1))
#'
#' # Fails and retries, then gives up:
#' \dontrun{
#' retry(function() sum(1, "a"), max_attempts = 2)
#' }
retry <- function(fn, max_attempts = getOption("refinitiv_max_retries", 2L),
                  backoff = 0.5, on_failure = c("stop", "NA")) {
  on_failure <- match.arg(on_failure)
  max_attempts <- as.integer(max_attempts)
  if (is.na(max_attempts) || max_attempts < 1L) max_attempts <- 1L

  last_error <- NULL
  # Sentinel: distinguishes "fn() returned NULL" from "fn() threw an error"
  .sentinel <- structure(list(), class = "retry_error_sentinel")

  for (i in seq_len(max_attempts)) {
    result <- tryCatch(fn(), error = function(e) {
      last_error <<- e
      message(
        "API request failed (attempt ", i, "/", max_attempts, "): ",
        conditionMessage(e)
      )
      if (i < max_attempts) {
        Sys.sleep(backoff * (2^(i - 1)))
      }
      .sentinel
    })
    if (!inherits(result, "retry_error_sentinel")) {
      return(result)
    }
  }

  # All attempts exhausted
  err_detail <- if (!is.null(last_error)) conditionMessage(last_error) else "unknown error"
  msg <- paste0("All ", max_attempts, " retry attempts failed. Last error: ", err_detail)

  if (on_failure == "stop") {
    stop(msg, call. = FALSE)
  }
  warning(msg, call. = FALSE)
  NA
}


#' Function to obtain timeseries from Eikon via the JSON API
#'
#' Automatically chunks the timeseries in seperate apicalls and binds them together again in order to comply with api regulations.
#'
#' @param EikonObject Eikon connection object. Defaults to \code{rd_connection()},
#'   which auto-creates a connection on first use.
#' @param rics a vector containing Reuters rics
#' @param interval Data interval. Possible values: 'tick', 'minute', 'hour', 'daily', 'weekly', 'monthly', 'quarterly', 'yearly'  Default: 'daily'
#' @param calender Possible values: 'native', 'tradingdays', 'calendardays'., Default: 'tradingdays'
#' @param fields a vector containing  any combination ('TIMESTAMP', 'VOLUME', 'HIGH', 'LOW', 'OPEN', 'CLOSE')
#' @param start_date Starting date and time of the historical range. string format is: '\%Y-\%m-\%dT\%H:\%M:\%S'.
#' @param end_date  End date and time of the historical range.  string format is: '\%Y-\%m-\%dT\%H:\%M:\%S'.
#' @param cast  cast data from wide to long format using the data.table::dcast function, Default: TRUE
#' @param time_out set the maximum timeout to the Eikon server, default = 60
#' @param verbose boolean if TRUE prints out the API call details to the console
#' @param raw_output provide only the raw downloaded info from Eikon
#' @param corax possible values 'adjusted', 'unadjusted'. Default: 'adjusted'
#' @param cache Controls caching. \code{NULL} (default) defers to
#'   \code{getOption("refinitiv_cache", FALSE)}. \code{TRUE} uses the
#'   function default TTL (300 s). \code{FALSE} disables caching. A positive
#'   numeric value sets the cache TTL in seconds. See \code{\link{rd_ClearCache}}.
#'
#' @importFrom utils capture.output head
#' @importFrom data.table `:=`
#'
#' @return A data.frame containing time series from Eikon
#' @export
#'
#' @references \url{https://developers.refinitiv.com/eikon-apis/eikon-data-api/docs?content=49692&type=documentation_item}
#' @importFrom  data.table rbindlist dcast
#' @examples
#' \dontrun{
#' Eikon <- Refinitiv::EikonConnect()
#' ex1 <- EikonGetTimeseries(
#'   EikonObject = Eikon, rics = c("MMM", "III.L"),
#'   start_date = "2020-01-01T01:00:00",
#'   end_date = paste0(Sys.Date(), "T01:00:00"), verbose = TRUE
#' )
#' }
#'
#' \dontrun{
#' EikonJson <- RefinitivJsonConnect()
#' ex1 <- EikonGetTimeseries(
#'   EikonObject = EikonJson, rics = c("MMM", "III.L"),
#'   start_date = "2020-01-01T01:00:00",
#'   end_date = paste0(Sys.Date(), "T01:00:00"), verbose = TRUE
#' )
#' }
#'
EikonGetTimeseries <- function(
  EikonObject = rd_connection(), rics, interval = "daily", calender = "tradingdays", corax = "adjusted", fields = c("TIMESTAMP", "VOLUME", "HIGH", "LOW", "OPEN", "CLOSE"),
  start_date = "2020-01-01T01:00:00", end_date = paste0(Sys.Date(), "T01:00:00"), cast = TRUE, time_out = 60, verbose = FALSE, raw_output = FALSE,
  cache = NULL
) {
  # ── Cache lookup ──
  ttl <- resolve_cache(cache, fn_default_ttl = 300)
  if (!isFALSE(ttl)) {
    .ck <- cache_key(
      "EikonGetTimeseries", rics, interval, calender, corax,
      fields, start_date, end_date, cast, raw_output
    )
    .hit <- cache_get(.ck)
    if (.hit$found) {
      if (verbose) message("[RefinitivR] Cache hit")
      return(.hit$value)
    }
  }

  try(EikonObject$set_app_key(app_key = refinitiv_vault_get("api_key")), silent = TRUE)

  # In case no rics are supplied return nothing
  if (is.null(rics)) {
    warning("no rics are supplied to EikonGetTimeseries")
    return(data.frame())
  }

  # make sure that TIMESTAMP is in fields if fields is not null
  if (!is.null(fields)) {
    fields <- unique(c("TIMESTAMP", fields))
  }

  # Make sure that monthly economic time series are returned
  if (any(grepl(pattern = "=", x = rics))) {
    fields <- unique(c("VALUE", fields))
  }


  # Convert as posix
  start_date <- as.POSIXct(start_date, format = "%Y-%m-%dT%H:%M:%S")
  end_date <- as.POSIXlt(end_date, format = "%Y-%m-%dT%H:%M:%S")

  ChunckedRics <- EikonTimeSeriesPreprocessor(interval = interval, rics = rics, start_date = start_date, end_date = end_date)

  eikon_ts_is_success <- function(x) {
    !identical(x, NA) && !identical(x, structure(list(), names = character(0)))
  }

  TimeSeriesList <- chunked_download(
    n_chunks = length(ChunckedRics),
    fetch_fn = function(j) {
      if (verbose) {
        message(paste0(
          Sys.time(), "\n",
          "EikonGetTimeseries JSON request:\n",
          "  rics      = [\"", paste(ChunckedRics[[j]], collapse = "\",\""), "\"]\n",
          "  interval  = \"", interval, "\"\n",
          "  calendar  = \"", calender, "\"\n",
          "  fields    = [\"", paste(fields, collapse = "\",\""), "\"]\n",
          "  start_date = \"", format(start_date, format = "%Y-%m-%dT%H:%M:%S"), "\"\n",
          "  end_date   = \"", format(end_date, format = "%Y-%m-%dT%H:%M:%S"), "\"\n",
          "  corax     = \"", corax, "\""
        ))
      }

      result <- if (is.null(fields) || length(fields) == 0L) {
        retry(function() {
          EikonObject$get_timeseries(
            rics       = ChunckedRics[[j]],
            interval   = interval,
            calendar   = calender,
            fields     = c(),
            start_date = format(start_date, format = "%Y-%m-%dT%H:%M:%S"),
            end_date   = format(end_date, format = "%Y-%m-%dT%H:%M:%S"),
            normalize  = TRUE,
            raw_output = TRUE,
            corax      = corax
          )
        }, max_attempts = 1L, on_failure = "NA")
      } else {
        retry(function() {
          EikonObject$get_timeseries(
            rics       = ChunckedRics[[j]],
            interval   = interval,
            calendar   = calender,
            fields     = fields,
            start_date = format(start_date, format = "%Y-%m-%dT%H:%M:%S"),
            end_date   = format(end_date, format = "%Y-%m-%dT%H:%M:%S"),
            normalize  = TRUE,
            raw_output = TRUE,
            corax      = corax
          )
        }, max_attempts = 1L, on_failure = "NA")
      }

      InspectRequest(df = result, functionname = "EikonGetTimeseries", verbose = verbose)
      result
    },
    is_success = eikon_ts_is_success,
    sleep = 0.5,
    on_failure = "warning",
    verbose = verbose,
    fail_message = "EikonGetTimeseries downloading data failed for one or more Rics"
  )

  ReturnElement <- if (raw_output) {
    TimeSeriesList
  } else {
    PostProcessTimeSeriesRequest(TimeSeriesList)
  }

  # ── Cache store (skip errors / NULL) ──
  if (!isFALSE(ttl) && !is.null(ReturnElement) && !inherits(ReturnElement, "try-error")) {
    cache_set(.ck, ReturnElement, ttl)
  }

  return(ReturnElement)
}


#' Function to obtain data from Eikon via the JSON API
#'
#' The function automatically chunks the list of rics into chunks that comply with the api limitations and in the end rebuilds the chunks again into a single data.frame.
#'
#'
#' @param EikonObject Eikon connection object. Defaults to \code{rd_connection()},
#'   which auto-creates a connection on first use.
#' @param rics a vector containing the instrument RICS
#' @param Eikonformulas a vector containing character string of Eikon Formulas
#' @param Parameters a named key value list for setting parameters, Default: NULL
#' @param raw_output to return the raw list by chunk for debugging purposes, default = FALSE
#' @param time_out set the maximum timeout to the Eikon server, default = 60
#' @param verbose boolean, set to TRUE to print out the API call details with time stamp for debugging.
#' @param SpaceConvertor converts spaces in variables name into one of the following characters ".", "," , "-", "_", default is "."
#' @param cache Controls caching. \code{NULL} (default) defers to
#'   \code{getOption("refinitiv_cache", FALSE)}. \code{TRUE} uses the
#'   function default TTL (300 s). \code{FALSE} disables caching. A positive
#'   numeric value sets the cache TTL in seconds. See \code{\link{rd_ClearCache}}.
#'
#' @return a data.frame containing data from Eikon
#' @importFrom utils capture.output
#'
#' @export
#' @references \url{https://developers.refinitiv.com/eikon-apis/eikon-data-api/docs?content=49692&type=documentation_item}
#'
#' @examples
#' \dontrun{
#' Eikon <- Refinitiv::EikonConnect()
#' ex1 <- EikonGetData(
#'   EikonObject = Eikon, rics = c("MMM", "III.L"),
#'   Eikonformulas = c(
#'     "TR.PE(Sdate=0D)/*P/E (LTM) - Diluted Excl*/",
#'     "TR.CompanyName"
#'   ), verbose = TRUE
#' )
#'
#' ex2 <- EikonGetData(
#'   EikonObject = Eikon, rics = "AAPL.O",
#'   Eikonformulas = "TR.CompanyMarketCap(Sdate=0D)/*Market Cap*/"
#' )
#'
#' # ex2 will return -1 which is most likely not the current market cap of apple")
#' # a workaround is to scale back the output to millions
#'
#' ex2a <- EikonGetData(
#'   EikonObject = Eikon, rics = "AAPL.O",
#'   Eikonformulas = "TR.CompanyMarketCap(Sdate=0D)/*Market Cap*/",
#'   Parameters = list("scale" = 6)
#' )
#' # or for more complex formula's
#' # scale back in the formula itself
#' ex2b <- EikonGetData(
#'   EikonObject = Eikon, rics = "AAPL.O",
#'   Eikonformulas = "TR.CompanyMarketCap(Sdate=0D, scale=6)/*Market Cap*/"
#' )
#' }
#'
#' \dontrun{
#' EikonJson <- RefinitivJsonConnect()
#' ex1 <- EikonGetData(
#'   EikonObject = EikonJson, rics = c("MMM", "III.L"),
#'   Eikonformulas = c(
#'     "TR.PE(Sdate=0D)/*P/E (LTM) - Diluted Excl*/",
#'     "TR.CompanyName"
#'   ), verbose = TRUE
#' )
#' }
#'
EikonGetData <- function(
  EikonObject = rd_connection(), rics, Eikonformulas, Parameters = NULL, raw_output = FALSE, time_out = 60, verbose = FALSE, SpaceConvertor = ".",
  cache = NULL
) {
  # ── Cache lookup ──
  ttl <- resolve_cache(cache, fn_default_ttl = 300)
  if (!isFALSE(ttl)) {
    .ck <- cache_key(
      "EikonGetData", rics, Eikonformulas, Parameters,
      raw_output, SpaceConvertor
    )
    .hit <- cache_get(.ck)
    if (.hit$found) {
      if (verbose) message("[RefinitivR] Cache hit")
      return(.hit$value)
    }
  }

  try(EikonObject$set_app_key(app_key = refinitiv_vault_get("api_key")), silent = TRUE)

  # Divide RICS in chunks to satisfy api limits
  ChunckedRics <- EikonChunker(RICS = rics, Eikonfields = Eikonformulas, MaxRicsperChunk = 200)


  eikon_data_is_success <- function(x) {
    !identical(x, NA) && !identical(x, structure(list(), names = character(0)))
  }

  EikonDataList <- chunked_download(
    n_chunks = length(ChunckedRics),
    fetch_fn = function(j) {
      if (verbose) {
        message(paste0(
          Sys.time(), "\n",
          "EikonGetData JSON request:\n",
          "  instruments = [\"", paste(ChunckedRics[[j]], collapse = "\",\""), "\"]\n",
          "  fields      = [\"", paste(Eikonformulas, collapse = "\",\""), "\"]"
        ))
      }

      result <- retry(function() {
        EikonObject$get_data(
          instruments = ChunckedRics[[j]],
          fields      = as.list(Eikonformulas),
          parameters  = Parameters,
          debug       = FALSE,
          raw_output  = TRUE
        )
      }, max_attempts = 1L, on_failure = "NA")

      InspectRequest(df = result, functionname = "EikonGetData", verbose = verbose)
      result
    },
    is_success = eikon_data_is_success,
    sleep = 0.5,
    verbose = verbose,
    fail_message = "EikonGetData downloading data failed"
  )


  if (!raw_output) {
    EikonDataList <- lapply(EikonDataList, FUN = function(x) {
      if (all(is.na(x))) {
        return(NULL)
      } else {
        return(x)
      }
    })
    ReturnElement <- new_EikonResult(EikonPostProcessor(EikonDataList, SpaceConvertor))
  } else {
    ReturnElement <- EikonDataList
  }

  # ── Cache store (skip errors / NULL) ──
  if (!isFALSE(ttl) && !is.null(ReturnElement) && !inherits(ReturnElement, "try-error")) {
    cache_set(.ck, ReturnElement, ttl)
  }

  return(ReturnElement)
}


# #' @param debug boolean When set to TRUE, the json request and response are printed.


#' Returns a list of instrument names converted into another instrument code.
#' For example: convert SEDOL instrument names to RIC names
#'
#'
#' @param EikonObject Eikon connection object. Defaults to \code{rd_connection()},
#'   which auto-creates a connection on first use.
#' @param symbol character or list of characters 	Single instrument or list of instruments to convert.
#' @param from_symbol_type character Instrument code to convert from. Possible values: 'CUSIP', 'ISIN', 'SEDOL', 'RIC', 'ticker', 'lipperID', 'IMO' Default: 'RIC'
#' @param to_symbol_type character  string or list 	Instrument code to convert to. Possible values: 'CUSIP', 'ISIN', 'SEDOL', 'RIC', 'ticker', 'lipperID', 'IMO', 'OAPermID' Default: None (means all symbol types are requested)
#' @param raw_output boolean 	Set this parameter to True to get the data in json format if set to FALSE, the function will return a data frame Default: FALSE
#' @param bestMatch boolean 	When set to TRUE, only primary symbol is requested. When set to FALSE, all symbols are requested
#' @param time_out numeric set the maximum timeout to the Eikon server, default = 60
#' @param verbose boolean, set to TRUE to print out the API call details with time stamp for debugging.
#' @param cache Controls caching. \code{NULL} (default) defers to
#'   \code{getOption("refinitiv_cache", FALSE)}. \code{TRUE} uses the
#'   function default TTL (3600 s / 1 hour). \code{FALSE} disables caching.
#'   A positive numeric value sets the cache TTL in seconds.
#'   See \code{\link{rd_ClearCache}}.
#'
#' @return data.frame
#' @export
#'
#' @examples
#' \dontrun{
#' Eikon <- Refinitiv::EikonConnect()
#' ex1 <- EikonGetSymbology(
#'   EikonObject = Eikon, symbol = "AAPL.O",
#'   to_symbol_type = "ISIN"
#' )
#' ex2 <- EikonGetSymbology(
#'   EikonObject = Eikon,
#'   symbol = "GB00B03MLX29", from_symbol_type = "ISIN",
#'   to_symbol_type = "RIC", verbose = TRUE
#' )
#' ex3 <- EikonGetSymbology(
#'   EikonObject = Eikon,
#'   symbol = "GB00B03MLX29", from_symbol_type = "ISIN",
#'   to_symbol_type = "RIC", verbose = TRUE, bestMatch = FALSE
#' )
#' ex4 <- EikonGetSymbology(
#'   EikonObject = Eikon, symbol = "RDSa.AS",
#'   to_symbol_type = "ISIN", verbose = TRUE
#' )
#' ex5 <- EikonGetSymbology(
#'   EikonObject = Eikon, symbol = "RDSa.L",
#'   to_symbol_type = "ISIN", verbose = TRUE
#' )
#' ex6 <- EikonGetSymbology(
#'   EikonObject = Eikon,
#'   symbol = c("GB00B03MLX29", "NL0015476987"), from_symbol_type = "ISIN",
#'   to_symbol_type = "RIC", verbose = TRUE, bestMatch = FALSE
#' )
#' ex7 <- EikonGetSymbology(
#'   EikonObject = Eikon,
#'   symbol = c("GB00B03MLX29", "US0378331005"), from_symbol_type = "ISIN",
#'   to_symbol_type = "RIC", verbose = TRUE, bestMatch = FALSE
#' )
#' }
#'
#' \dontrun{
#' EikonJson <- RefinitivJsonConnect()
#' ex1 <- EikonGetSymbology(
#'   EikonObject = EikonJson, symbol = "AAPL.O",
#'   to_symbol_type = "ISIN"
#' )
#' }
#'
EikonGetSymbology <- function(
  EikonObject = rd_connection(), symbol, from_symbol_type = "RIC", to_symbol_type = c("CUSIP", "ISIN", "SEDOL", "RIC", "ticker", "lipperID", "IMO", "OAPermID"),
  bestMatch = TRUE, time_out = 60, verbose = FALSE, raw_output = FALSE,
  cache = NULL
) {
  # ── Cache lookup ──
  ttl <- resolve_cache(cache, fn_default_ttl = 3600)
  if (!isFALSE(ttl)) {
    .ck <- cache_key(
      "EikonGetSymbology", symbol, from_symbol_type, to_symbol_type,
      bestMatch, raw_output
    )
    .hit <- cache_get(.ck)
    if (.hit$found) {
      if (verbose) message("[RefinitivR] Cache hit")
      return(.hit$value)
    }
  }

  try(EikonObject$set_app_key(app_key = refinitiv_vault_get("api_key")), silent = TRUE)

  # Divide symbols in chunks to satisfy api limits
  ChunckedSymbols <- EikonChunker(RICS = symbol, Eikonfields = to_symbol_type)

  EikonSymbologyList <- chunked_download(
    n_chunks = length(ChunckedSymbols),
    fetch_fn = function(j) {
      if (verbose) {
        message(paste0(
          Sys.time(), "\n",
          "EikonGetSymbology JSON request:\n",
          "  symbol          = [\"", paste(ChunckedSymbols[[j]], collapse = "\",\""), "\"]\n",
          "  from_symbol_type = [\"", paste(from_symbol_type, collapse = "\",\""), "\"]\n",
          "  to_symbol_type   = [\"", paste(to_symbol_type, collapse = "\",\""), "\"]\n",
          "  bestMatch       = ", bestMatch
        ))
      }

      result <- retry(function() {
        EikonObject$get_symbology(
          symbol           = ChunckedSymbols[[j]],
          from_symbol_type = from_symbol_type,
          to_symbol_type   = list(to_symbol_type),
          raw_output       = TRUE,
          debug            = FALSE,
          best_match       = bestMatch
        )
      }, max_attempts = 1L, on_failure = "NA")

      InspectRequest(df = result, functionname = "EikonGetSymbology", verbose = verbose)
      result
    },
    sleep = 0.5,
    on_failure = "warning",
    verbose = verbose,
    fail_message = "EikonGetSymbology downloading data failed for one or more symbols"
  )


  if (!raw_output) {
    EikonSymbologyList <- lapply(EikonSymbologyList, FUN = function(x) {
      if (all(is.na(x))) {
        return(NULL)
      } else {
        return(x)
      }
    })
    ReturnElement <- ProcessSymbology(EikonSymbologyList, from_symbol_type = from_symbol_type, to_symbol_type = to_symbol_type)
  } else {
    ReturnElement <- EikonSymbologyList
  }

  # ── Cache store (skip errors / NULL) ──
  if (!isFALSE(ttl) && !is.null(ReturnElement) && !inherits(ReturnElement, "try-error")) {
    cache_set(.ck, ReturnElement, ttl)
  }

  return(ReturnElement)
}


#' function to check if a downloaded dataframe is empty
#'
#' @param df data.frame
#' @param functionname function name for error reporting
#' @param verbose Boolean print or not variable
#'
#' @importFrom utils capture.output
#' @importFrom utils head
#' @importFrom utils str
#' @return boolean
#' @keywords internal
#'
#' @examples
#' Refinitiv:::InspectRequest(data.frame(), functionname = "test")
#' Refinitiv:::InspectRequest(data.frame(test = c(1, 2), test2 = c("a", "b")), functionname = "test")
InspectRequest <- function(df, functionname, verbose = TRUE) {
  if (!verbose) {
    return(NULL)
  }


  try(message(class(df)))
  try(message(names(df)))
  try(message(lapply(df, names)))

  if (is.logical(df) && is.na(df)) {
    try(message(paste0(functionname, " request returned NA")))
  }

  if (("error" %in% names(df))) {
    try(message(paste0(functionname, " request returned the following (and other) erors: ", paste(capture.output(head(data.table::rbindlist(df$error), 10)), collapse = "\n"))))
  }

  if ("totalRowsCount" %in% names(df) && "totalColumnsCount" %in% names(df)) {
    try(message(paste0(functionname, " request returned the following data: ", df$totalColumnsCount, " columns and ", df$totalRowsCount, " rows")))
  }

  if (length(df) != 0) {
    try(message(paste0(functionname, " request returned with length ", length(df))))
  } else {
    try(message(paste0(functionname, " request returned with length 0")))
  }
}
