on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release', python: '3.10'}
          - {os: windows-latest, r: 'release', python: '3.10'}
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release', python: '3.10'}
          - {os: ubuntu-latest,  r: 'release', python: '3.10'}
       
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config.python }}

      - uses: conda-incubator/setup-miniconda@v3
        with:
             auto-activate-base: true
             activate-environment: "r-eikon"
             python-version: "3.10"

      - name: Install Python Packages in Conda
        run: |
          conda install -n r-eikon -c conda-forge docutils pandas scipy matplotlib ipython tabulate plotly psutil kaleido wrapt
          conda list  # Verify installation

      - name: setup r-reticulate conda env
        shell: Rscript {0}
        run: |
          library(reticulate)
          use_condaenv("r-eikon", required = TRUE)
          py_config()

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck local::.
          cache-version: 4
          upgrade: 'TRUE'

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
