on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release', python: '3.10'}
          - {os: windows-latest, r: 'release', python: '3.10'}
          - {os: ubuntu-latest,  r: 'devel', python: '3.10'}
          - {os: ubuntu-latest,  r: 'release', python: '3.10'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config.python }}  # Explicitly set Python version

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: "r-eikon"
          python-version: "3.10"

      - name: Verify Conda Installation
        run: |
          conda --version
          which conda
        shell: bash

      - name: Install Python Packages (Mac & Ubuntu)
        if: runner.os != 'Windows'
        run: |
          conda install -n r-eikon -c conda-forge docutils pandas scipy matplotlib ipython tabulate plotly psutil numpy
          pip install kaleido wrapt
          conda list  # Verify installation

      - name: Install Python Packages (Windows)
        if: runner.os == 'Windows'
        run: |
          conda install -n r-eikon -c conda-forge docutils pandas scipy matplotlib ipython tabulate plotly psutil numpy
          # Note: Kaleido is not installed on Windows in this step
          conda list  # Verify installation

      - name: Install R Dependencies
        run: |
          Rscript -e "install.packages('reticulate')"
        if: runner.os == 'Windows' || runner.os == 'Linux'  # Ensure reticulate is installed everywhere

      - name: Setup R-Reticulated Conda Environment
        shell: Rscript {0}
        run: |
          library(reticulate)
          use_condaenv("r-eikon", required = TRUE)
          py_config()

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck local::.
          cache-version: 4
          upgrade: 'TRUE'

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
