on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release', python: '3.10'}
          - {os: windows-latest, r: 'release', python: '3.10'}
          - {os: ubuntu-latest,  r: 'devel', python: '3.10'}
          - {os: ubuntu-latest,  r: 'release', python: '3.10'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config.python }}

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3  # Updated to the latest available version
        with:
          auto-activate-base: true
          activate-environment: "r-eikon"
          python-version: "3.10"

      - name: Verify Conda Installation
        run: |
          conda --version
          which conda || echo "Conda not found in PATH"
        shell: bash

      - name: Install Python Packages
        run: |
          conda install -n r-eikon -c conda-forge docutils pandas scipy matplotlib ipython 
