name: test-coverage

on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: read

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: "r-eikon"
          python-version: "3.10"

      - name: Install Python Packages
        run: |
          conda install -n r-eikon -c conda-forge docutils pandas scipy matplotlib ipython tabulate plotly psutil numpy
          pip install kaleido wrapt
          conda list

      - name: Install R Packages and Reticulate
        run: |
          Rscript -e "install.packages(c('covr','xml2','reticulate'))"

      - name: Setup R-Reticulated Conda Environment and Verify Python Config
        run: |
          Rscript -e "library(reticulate); use_condaenv('r-eikon', required = TRUE); py_config()"

      - name: Test coverage
        run: |
          Rscript -e "if (!requireNamespace('remotes', quietly = TRUE)) install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, upgrade = 'always')"
          Rscript -e "cov <- covr::package_coverage(clean = FALSE, quiet = FALSE); print(cov); covr::to_cobertura(cov)"

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
